# Generated by Django 5.0.1 on 2024-02-04 21:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('operation', models.CharField(max_length=20)),
                ('old_volume_percentage', models.IntegerField()),
                ('new_volume_percentage', models.IntegerField()),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waste_app.wastestation')),
            ],
        ),
    ]
